### PR TITLE
ensure => exported with array_type/append does not work as expected

### PR DESCRIPTION
**Pull request by raphink**
# file (before):
export JAVA_OPTIONS="-server -Xms512m"

# modification
shellvar { "JAVA_OPTIONS":
  ensure       => exported,                                                                    
  target       => "file",
  value        => ["-Djavax.net.ssl.trustStore=test"],
  array_type   => "string",
  array_append => true,
}

# file (after):
JAVA_OPTIONS="-server -Xms512m -Djavax.net.ssl.trustStore=test"

# used components
Puppet client+server: 3.4.3
herculesteam-augeasproviders_core (v2.1.1)
herculesteam-augeasproviders_shellvar (v2.1.1)

### CODE REVIEW

**Comment by raphink** [comment]
I've added some code to this issue, which I believe should fix it.

It seems for some reason that it only converges in two runs though, causing the unit tests to fail. @domcleal do you have any idea why the value's `insync?` is not triggered on the first run?

**Comment by raphink** [comment]
It seems properties are only synced in the `ensure` property is already in sync…

**Comment by raphink** [comment]
I've added a manual sync of `value` when property is unset or exported, but I'm not sure if this is the best way to do it (at least, it fixes the issue).

**Comment by raphink** [comment]
@domcleal what do you think of the solution?

**Comment by domcleal** [comment]
@raphink I'm a bit out of it so can't comment much..

**Comment by raphink** [comment]
@domcleal what do you think of https://github.com/raphink/augeasproviders_shellvar/commit/353bbf9884f3be88a3f8eed5da7bd3e820567b5d? Do you know of another way to do that?

**Comment by domcleal** [comment]
No, unless you can call the underlying provider methods directly there, or inside the provider itself - but it looks convoluted, so probably not easy.

**Pull request closed without merging**
